# -*- coding: utf-8 -*-
"""AI News Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nexKcAFS3-udqQa3zxQIlHQWtgC9vJx0
"""

!pip install feedparser newspaper3k transformers torch lxml_html_clean --quiet

import feedparser
from newspaper import Article
from transformers import pipeline
from datetime import datetime
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from transformers import pipeline

summarizer = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("Model Loaded Successfully")

rss_feeds = [
    "https://feeds.bbci.co.uk/news/rss.xml",
    "https://rss.cnn.com/rss/edition.rss",
    "https://feeds.reuters.com/reuters/topNews",
    "https://www.thehindu.com/news/national/feeder/default.rss",
    "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms"
]

print("RSS feeds loaded")

article_links = []

for feed_url in rss_feeds:
    feed = feedparser.parse(feed_url)

    for entry in feed.entries[:10]:
        if entry.link not in article_links:
            article_links.append(entry.link)

print(f"Total Articles Collected: {len(article_links)}")

news_articles = []

keywords_to_ignore = [
    "advertisement",
    "sponsored",
    "watch live",
    "video",
    "photos"
]

for link in article_links:
    try:
        article = Article(link)

        article.download()
        article.parse()

        title = article.title.strip()
        text = article.text.strip()

        # Ignore weak/noisy articles
        if (
            len(text) < 500
            or any(word.lower() in title.lower() for word in keywords_to_ignore)
        ):
            continue

        news_articles.append({
            "title": title,
            "text": text[:2000],
            "link": link
        })

        print("Collected:", title)

    except:
        pass

print(f"\nTotal Clean Articles: {len(news_articles)}")

combined_news = ""

for article in news_articles:
    combined_news += article["title"] + "\n"
    combined_news += article["text"][:1500] + "\n\n"

print("Combined News Length:", len(combined_news))

from transformers import pipeline

# -----------------------------------
# LOAD AI CLASSIFIER
# -----------------------------------

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

# -----------------------------------
# CATEGORY LABELS
# -----------------------------------

candidate_labels = [
    "Global News",
    "Business & Economy",
    "Technology & AI",
    "India"
]

# -----------------------------------
# EMPTY CATEGORY SECTIONS
# -----------------------------------

categorized_news = {
    "🌍 GLOBAL NEWS": [],
    "💼 BUSINESS & ECONOMY": [],
    "🤖 TECHNOLOGY & AI": [],
    "🇮🇳 INDIA": [],
    "📌 OTHER IMPORTANT UPDATES": []
}

# -----------------------------------
# FORCE GLOBAL NEWS KEYWORDS
# -----------------------------------

global_keywords = [
    "war", "ukraine", "russia", "china",
    "israel", "gaza", "nato", "iran",
    "world", "global", "europe", "un",
    "united nations", "military", "attack",
    "conflict", "ceasefire", "tariff"
]

# -----------------------------------
# CLASSIFY ARTICLES
# -----------------------------------

for article in news_articles:

    headline = article["title"]
    headline_lower = headline.lower()

    assigned = False

    # -----------------------------------
    # FORCE GLOBAL NEWS
    # -----------------------------------

    if any(keyword in headline_lower for keyword in global_keywords):

        categorized_news["🌍 GLOBAL NEWS"].append(article)
        assigned = True

    # -----------------------------------
    # AI CLASSIFICATION
    # -----------------------------------

    if not assigned:

        try:

            result = classifier(
                headline,
                candidate_labels
            )

            category = result["labels"][0]

        except Exception:
            category = "Other"

        # -----------------------------------
        # MAP AI CATEGORY
        # -----------------------------------

        if category == "Business & Economy":

            categorized_news["💼 BUSINESS & ECONOMY"].append(article)

        elif category == "Technology & AI":

            categorized_news["🤖 TECHNOLOGY & AI"].append(article)

        elif category == "India":

            categorized_news["🇮🇳 INDIA"].append(article)

        elif category == "Global News":

            categorized_news["🌍 GLOBAL NEWS"].append(article)

        else:

            categorized_news["📌 OTHER IMPORTANT UPDATES"].append(article)

# -----------------------------------
# GENERATE FINAL NEWS BRIEFING
# -----------------------------------

daily_summary = ""

section_order = [
    "🌍 GLOBAL NEWS",
    "💼 BUSINESS & ECONOMY",
    "🤖 TECHNOLOGY & AI",
    "🇮🇳 INDIA",
    "📌 OTHER IMPORTANT UPDATES"
]

for category in section_order:

    articles = categorized_news[category]

    if len(articles) == 0:
        continue

    daily_summary += f"\n{category}\n\n"

    for article in articles[:5]:

        daily_summary += (
            f"• {article['title']}\n"
            f"  {article['link']}\n\n"
        )

print("\n📰 DAILY AI NEWS BRIEFING\n")
print(daily_summary)

today = datetime.now().strftime("%Y-%m-%d")

filename = f"daily_news_summary_{today}.txt"

with open(filename, "w", encoding="utf-8") as f:
    f.write(daily_summary)

print(f"Summary saved as: {filename}")

from google.colab import files

files.download(filename)

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Your Gmail
sender_email = "ruhikakriti08@gmail.com"
receiver_email = "ruhikakriti08@gmail.com"

# Your 16-character Gmail App Password
password = "wmoqjuqyvhzoaxci"

# Create email message
message = MIMEMultipart("alternative")

message["Subject"] = "📰 Daily AI News Briefing"
message["From"] = sender_email
message["To"] = receiver_email

# HTML Email Design
html = f"""
<html>

<body style="font-family: Arial; padding: 20px; background-color: #f4f4f4;">

<div style="
    background-color: white;
    padding: 25px;
    border-radius: 10px;
    max-width: 800px;
    margin: auto;
    box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
">

<h1 style="color: #222;">
📰 Daily AI News Briefing
</h1>

<p style="color: #666;">
Your automated AI-generated news summary for today.
</p>

<hr>

<pre style="
    font-size: 15px;
    white-space: pre-wrap;
    line-height: 1.6;
    color: #333;
">
{daily_summary}
</pre>

<hr>

<p style="font-size: 13px; color: gray;">
Generated automatically using your AI News Agent
</p>

</div>

</body>
</html>
"""

# Attach HTML email
message.attach(MIMEText(html, "html"))

# Send Email
try:
    server = smtplib.SMTP("smtp.gmail.com", 587)

    server.ehlo()
    server.starttls()
    server.ehlo()

    server.login(sender_email, password)

    server.sendmail(
        sender_email,
        receiver_email,
        message.as_string()
    )

    server.quit()

    print("✅ Email sent successfully!")

except Exception as e:
    print("❌ Error:", e)
